comp_status:
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
in_directory:
  description: Input directory
  value:
    type: string
    default: permamodel/examples
    units: '-'
out_directory:
  description: Output directory
  value:
    type: string
    default: .
    units: '-'
permafrost_dir:
  description: permafrost directory
  value:
    type: string
    default: .
    units: '-'    
site_prefix:
  description: File prefix for the study site
  value:
    type: string
    default: Test
    units: '-'
case_prefix:
  description: File prefix for the model scenario
  value:
    type: string
    default: Case_test
    units: '-'

lat_ptype:
  description: Latitude
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: degN
lat_dtype:
  description: lat data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
lat:
  description: Scalar value
  value:
    type: float
    default: 64.8378
    range:
      min: -90.0
      max: 90.0
    units: degN
lat_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
lon_ptype:
  description: Longitude
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: degE
lon_dtype:
  description: lon data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
lon:
  description: Scalar value
  value:
    type: float
    default: -147.7164
    range:
      min: -180.0
      max: 180.0
    units: degE
lon_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'

start_year:
  description: begining of the simulation time 
  value:
    type: float
    default: 2009
    range:
      min: 0
      max: 100000000
    units: yr
end_year:
  description: end of the simulation time 
  value:
    type: float
    default: 2009
    range:
      min: 0
      max: 100000000
    units: yr
dt:
  description: Timestep for infiltration process (a year)
  value:
    type: float
    default: 31536000.000
    range:
      min: 0
      max: 1e12
    units: s

T_air_ptype:
  description: Near-surface air temperature (annual mean)
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: degC
T_air_dtype:
  description: T_air data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
T_air:
  description: Scalar value
  value:
    type: float
    default: -9.0
    range:
      min: -100.0
      max: 100.0
    units: degC
T_air_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
A_air_ptype:
  description: Near-surface air temperature amplitude (annual mean)
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: degC
A_air_dtype:
  description: A_air data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
A_air:
  description: Scalar value
  value:
    type: float
    default: 15.4
    range:
      min: -100.0
      max: 100.0
    units: degC
A_air_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'

h_snow_ptype:
  description: Depth of snow (average through winter)
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: m
h_snow_dtype:
  description: h_snow data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
h_snow:
  description: Scalar value
  value:
    type: float
    default: 0.300
    range:
      min: 0.0
      max: 5.0
    units: m
h_snow_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
rho_snow_ptype:
  description: Density of snow (average through winter)
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: kg m-3
rho_snow_dtype:
  description: rho_snow data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
rho_snow:
  description: Scalar value
  value:
    type: float
    default: 240.000
    range:
      min: 0.0
      max: 1.0e3
    units: kg m-3
rho_snow_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'

vwc_H2O_ptype:
  description: Soil volumetric water content (thaw season; e.g., August)
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: '-'
vwc_H2O_dtype:
  description: vwc_H2O data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
vwc_H2O:
  description: Scalar value
  value:
    type: float
    default: 0.4
    range:
      min: 0.0
      max: 1.0
    units: '-'
vwc_H2O_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'

Hvgf_ptype:
  description: Height of vegetation in frozen period
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: m
Hvgf_dtype:
  description: Hvgf data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
Hvgf:
  description: Scalar value
  value:
    type: float
    default: 0.00
    range:
      min: 0.0
      max: 1.0
    units: m
Hvgf_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
Hvgt_ptype:
  description: Height of vegetation in thawed period
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: m
Hvgt_dtype:
  description: Hvgt data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
Hvgt:
  description: Scalar value
  value:
    type: float
    default: 0.00
    range:
      min: 0.0
      max: 1.0
    units: m
Hvgt_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
Dvf_ptype:
  description: Thermal diffusivity of vegetation in frozen period
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: 'm2 s'
Dvf_dtype:
  description: Dvf data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
Dvf:
  description: Scalar value
  value:
    type: float
    default: 1.39E-6
    range:
      min: 0.0
      max: 5.0E-6
    units: 'm2 s'
Dvf_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'
Dvt_ptype:
  description: Thermal diffusivity of vegetation in thawed period
  value:
    type: choice
    default: Scalar
    choices:
      - Scalar
      - Time_Series
    units: 'm2 s'
Dvt_dtype:
  description: Dvt data type
  value:
    type: choice
    default: float
    choices:
      - float
      - string
    units: '-'
Dvt:
  description: Scalar value
  value:
    type: float
    default: 5.56E-8
    range:
      min: 0.0
      max: 1.0E-6
    units: 'm2 s'
Dvt_file:
  description: Time series file
  value:
    type: file
    default: 'off'
    files:
      - 'off'


SAVE_ALT_GRIDS:
  description: option to save result or not
  value:
    type: choice
    default: No
    choices:
    - Yes
    - No
ALT_file:
  description: Name of output file
  value:
    type: string
    default: ALT.nc
