Input:
- key: permafrost_dir
  name: permafrost root directory 
  description: Directory containing permamodel files
  value:
    type: string
    default: .
    units: '-'
- key: comp_status
  name: Component status
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
- key: in_directory
  name: Input directory
  description: Input directory
  value:
    type: string
    default: .
    units: '-'
- key: out_directory
  name: Output directory
  description: Output directory
  value:
    type: string
    default: .
    units: '-'
- key: site_prefix
  name: Site prefix
  description: File prefix for the study site
  value:
    type: string
    default: Test
    units: '-'
- key: case_prefix
  name: Case prefix
  description: File prefix for the model scenario
  value:
    type: string
    default: Case_test
    units: '-'
- key: T_air_min_type
  name: T_air_min type
  description: data type of T_air_min
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Time_Series
    units: '-'
- key: T_air_min
  name: T_air_min
  description:  Average temp of coldest month in the modeled year
  value:
    type: float
    default: '-9.0'
    range:
      min: '-100.0'
      max: 100
    units: degC
- key: T_air_max_type
  name: T_air_max type
  description: date type of T_air_max
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Time_Series
    units: '-'
- key: T_air_max
  name: T_air_max
  description:  Average temp of warmest month in the modeled year
  value:
    type: float
    default: '15.4'
    range:
      min: '-100.0'
      max: 100
    units: degC
- key: start_year
  name: start year
  description: begining of the simulation time 
  value:
    type: float
    default: '2000'
    range:
      min: 1000
      max: 2200
    units: year
- key: end_year
  name: end year
  description: end of the simulation time 
  value:
    type: float
    default: '2000'
    range:
      min: 1000
      max: 2200
    units: year
- key: dt
  name: Time step
  description: Timestep for permamodel
  value:
    type: float
    default: 1.0
    range:
      min: '0.001'
      max: 1e3
    units: year
Output:
- key: frostnumber_air
  name: frostnumber_air
  description: Current value of the air frost number
  value:
    type: float
    units: '-'
- key: frostnumber_surface
  name: frostnumber_surface
  description: Current value of the surface frost number
  value:
    type: float
    units: '-'
- key: frostnumber_stefan
  name: frostnumber_stefan
  description: Current value of the Stefan frost number
  value:
    type: float
    units: '-'
- key: output_dictionary
  name: output_dictionary
  description: Data structure--a dictionary--with the results of the model run
  value:
    type: dictionary
    units: '-'
- key: fn_out_filename
  name: fn_out_filename
  description: Filename to which model output is saved at the end of the run
  value:
    type: string
    units: '-'
About:
- key: PermaModel FrostNumber
  name: PermaModel FrostNumber
  description: Computes the frost number for a location 
  value:
    type: String
    default: frost_model
    units: '-'
- key: ModelAuthor
  name: Author name
  description: Elchin Jafarov and J. Scott Stewart
  value:
    type: String
    default: 'Elchin Jafarov and J. Scott Stewart'
    units: '-'
- key: HTML_HELP_FILE
  name: HTML help file
  description: Url for html help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/
    units: '-'
