name: Format

on: [push, pull_request]

jobs:

  format:
    name: Check for lint and format code to a standard style
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
          src: "permamodel"
